apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: signal-sample
    app.kubernetes.io/managed-by: signal-controller
    app.kubernetes.io/name: axon-konduit-job
  name: signal-sample-job
  namespace: default
  ownerReferences:
  - apiVersion: axon.shlok.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Signal
    name: signal-sample
    uid: 346c7835-e362-4b0b-82a8-c103bf090394
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo Hello from the Axon-Konduit Job
            image: busybox
            name: job-container
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/5 * * * *'
status: {}
