apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: signal-sample
    app.kubernetes.io/managed-by: signal-controller
    app.kubernetes.io/name: axon-konduit-serving
  name: signal-sample-serving
  namespace: default
  ownerReferences:
  - apiVersion: axon.shlok.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Signal
    name: signal-sample
    uid: ccc2d898-dd7e-4414-9d71-7b25ce2f0cfa
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: signal-sample
      app.kubernetes.io/managed-by: signal-controller
      app.kubernetes.io/name: axon-konduit-serving
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: signal-sample
        app.kubernetes.io/managed-by: signal-controller
        app.kubernetes.io/name: axon-konduit-serving
    spec:
      containers:
      - image: nginx
        name: serving-container
        ports:
        - containerPort: 80
          name: http
        resources: {}
status: {}
