apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default-signal-sample
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: workloads/default/signal-sample
    repoURL: https://github.com/shlokc9/axon-konduit-config.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
