apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: signal-sample-job
  namespace: default
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - args:
            - /bin/sh
            - -c
            - date; echo Hello from the Axon-Konduit Job
            image: busybox
            name: job-container
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/6 * * * *'
status: {}
